version: '1.0'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./.env
    ports:
      - "8091:8091"
    depends_on:
      - postgres
    develop:
      watch:
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./.env
        - action: sync
          path: ./src
          target: /usr/src/app/src
    restart: always

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
